FROM php:8.4-cli
RUN pecl install redis \
    && docker-php-ext-enable redis

RUN apt-get update && apt-get install -y \
    git curl zip unzip libpq-dev libpng-dev libonig-dev libzip-dev libssl-dev pkg-config \
    supervisor build-essential libbrotli-dev \
    && docker-php-ext-install pdo pdo_pgsql zip gd opcache sockets pcntl \
    && pecl install swoole \
    && docker-php-ext-enable swoole

RUN echo "memory_limit=512M" > /usr/local/etc/php/conf.d/memory.ini

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . ./

RUN composer install --no-dev --prefer-dist --no-interaction --no-progress

EXPOSE 8000

CMD ["php", "artisan", "octane:start", "--server=swoole", "--host=0.0.0.0", "--port=8000", "--workers=4"]
