server {
    listen 80;
    server_name localhost;

    # Swagger / документация Laravel
    location ^~ /docs/ {
        alias /var/www/html/public/docs/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    location / {
            proxy_pass http://frontend:5173;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
    }
    # Статика Laravel storage
    location /storage/ {
        alias /var/www/html/storage/app/public/;
        try_files $uri $uri/ =404;

        # Кэширование для статических файлов
        expires 1y;
        add_header Cache-Control "public, immutable";

        # Безопасность
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";

        # CORS
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, OPTIONS';
        add_header Access-Control-Allow-Headers 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';

        # Обработка изображений
        location ~* \.(jpg|jpeg|png|gif|ico|webp|svg)$ {
            expires max;
            add_header Cache-Control "public, immutable";
        }
    }

    # Backend API через Laravel Octane (RoadRunner)
    location ~ ^/api/(.*)$ {
        proxy_pass http://backend:8000;  # Octane слушает 8000
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_set_header Upgrade $http_upgrade;

        # CORS
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header Access-Control-Allow-Headers 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
    }

    # Frontend Vite / production сборка


    # Favicon и robots
    location = /favicon.ico {
        alias /var/www/html/public/favicon.ico;
        expires max;
    }

    location = /robots.txt {
        alias /var/www/html/public/robots.txt;
        expires max;
    }
}
